name: Generate Share Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install (no deps needed)
        run: |
          echo "No dependencies to install"

      - name: Generate share pages
        env:
          SITE_BASE_URL: ${{ secrets.SITE_BASE_URL }}
        run: |
          node tools/generate-share-pages.js

      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add share/*.html
            git commit -m "chore: auto-generate share pages"
            git push
          fi
